version: "3"
services:
  mongo:
    image: mongo
    restart: always
  learn-todo:
    build: .
    command: npm start
    ports:
      - "9000:9000"
    volumes:
      - .:/usr/app
    depends_on: 
      - mongo
